FROM mcr.microsoft.com/dotnet/sdk:6.0
RUN export MARIADB_DB_ConnectionString=${MARIADB_DB_ConnectionString}
WORKDIR /webapi-app/bin
WORKDIR /webapi-app
COPY . .
RUN dotnet restore ./Docker.Volumes.MariaDbReuse.WebApi.csproj
RUN dotnet build --no-restore -c Release -o bin ./Docker.Volumes.MariaDbReuse.WebApi.csproj
WORKDIR bin
CMD dotnet Docker.Volumes.MariaDbReuse.WebApi.dll
