FROM mcr.microsoft.com/dotnet/sdk:6.0
# not sure this right to pass via BUILD arg - need to pass without rebuilding images with different Environments
ARG MARIADB_DB_ConnectionString
RUN echo $MARIADB_DB_ConnectionString > /test.txt
ENV MARIADB_DB_ConnectionString=$MARIADB_DB_ConnectionString
WORKDIR /webapi-app/bin
WORKDIR /webapi-app
COPY . .
RUN dotnet restore ./Docker.Volumes.MariaDbReuse.WebApi.csproj
RUN dotnet build --no-restore -c Release -o bin ./Docker.Volumes.MariaDbReuse.WebApi.csproj
WORKDIR bin
CMD dotnet Docker.Volumes.MariaDbReuse.WebApi.dll
