apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  labels:
    app: webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi-client
          image: webapi-client:1.1
          ports:
            - containerPort: 8081
          env:            
            ASPNETCORE_ENVIRONMENT: 
              valueFrom:
                configMapKeyRef:
                  name: configmap-demo 
                  key: environment 
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  selector:
    #app.kubernetes.io/name: MyApp
    app: webapi
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306