version: "3.9"

#just reference
x-docker-envs: &x-envs
 environment:
  - MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}  
  - ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
  - MARIADB_HOST: ${MARIADB_HOST}
  - MARIADB_DATABASE: ${MARIADB_DATABASE}
   
services:
 db:
  hostname: ${MARIADB_HOST}
  image: mariadb:10.7
  container_name: mariadb
  restart: always 
  environment:
   MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
   MARIADB_DATABASE: $MARIADB_DATABASE
  volumes:
   - E:\containers-data\maria-10.7:/var/lib/mysql
  networks:
  - mariadb-network
 
 webapi-client:
  image: webapi-client:1.1
  build:
   context: ../
   dockerfile: Docker/Dockerfile-webapi   
  container_name: webapi-client 
  restart: always
  environment:
   ASPNETCORE_ENVIRONMENT: $ENVIRONMENT
  ports:   
   - 8081:8081
  depends_on:
   - db
  networks:
   - mariadb-network

networks:
 mariadb-network: