version: "3.9"

services:
 db:
  image: mariadb:10.7
  container_name: db
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: example

 adminer:
  container_name: client
  image: adminer
  restart: always
  ports:
   - 8080:8080
