FROM mcr.microsoft.com/dotnet/sdk:6.0 as build-env
WORKDIR /webapi-app/bin
WORKDIR /webapi-app

COPY . .
RUN dotnet restore
RUN dotnet publish --no-restore -f net6.0 -c Release -o bin
RUN rm -rf bin/Release/net6.0/ref

# create final size-optimized image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
ENV Logging__Console__FormatterName=Simple
ENV ASPNETCORE_ENVIRONMENT=

WORKDIR /webapi-app
COPY --from=build-env /webapi-app/bin/Release/net6.0 .
ENTRYPOINT ["dotnet", "Docker.Volumes.MariaDbReuse.WebApi.dll"]