#according to: #https://vocon-it.com/2018/12/20/kubernetes-local-persistent-volumes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-local-pv
spec:
  capacity:
    storage: 30Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: E:\containers-data\webapi-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1